<?php
use User\Entity\User;

$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
]);
?>

<h1>Manage Users</h1>

<?= $this->partial('partial/flash-messages.phtml', 'application'); ?>

<p>
<a class="btn btn-default" href="
    <?= $this->url('users', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>E-mail</th>
        <th>Full Name</th>
        <th>Role(s)</th>        
        <th>Date Created</th>
        <th>Status</th>        
        <th>Actions</th>        
    </tr>

    <?php /** @var User $user */?>
    <?php foreach ($users as $user): ?>

    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>
        <td>
            <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getEmail()); ?>
            </a> 
        </td>
        <td>
            <?= $this->escapeHtml($user->getFullName()); ?></a> 
        </td>
        <td>
            <?= $this->escapeHtml($user->getRolesAsString()); ?></a> 
        </td>
        <td><nobr><?= $this->escapeHtml($user->getDateCreated()); ?></nobr></td>        
        <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('users', 
                    ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-default" href="<?= $this->url('users',
                    ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> Change Password
            </a>
            <?php
                if ($this->currentUser()->getEmail() !== $user->getEmail()
                    && $this->currentUser()->canImpersonate()
                    && $user->canBeImpersonated()
                ):
            ?>
                <a class="btn btn-info" href="<?= $this->url('impersonate',
                    ['action'=>'impersonate', 'id'=>$user->getId()]); ?>">
                    <span class="glyphicon glyphicon-user" ></span> Impersonate
                </a>
            <?php endif; ?>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

