<?php
$this->headTitle('Edit Role');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Roles'=>$this->url('roles'),
            'Edit Role ' . $role->getName() => $this->url('roles', ['action'=>'edit', 'id'=>$role->getId()])
            ]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter name'
]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter description'
]);

$form->get('inherit_roles')->setAttributes([
    'class'=>'form-control', 
]);

/** @var \Zend\Form\Element\Checkbox $canImpersonate */
$canImpersonate = $form->get('canImpersonate');

$canImpersonateAttributes = [];
$canImpersonateAttributes['style'] = 'display: block;';

if ($canImpersonate->isChecked()) {
    $canImpersonateAttributes['checked'] = 'checked';
}

$canImpersonate->setAttributes($canImpersonateAttributes);


/** @var \Zend\Form\Element\Checkbox $canBeImpersonated */
$canBeImpersonated = $form->get('canBeImpersonated');

$canBeImpersonatedAttributes = [];
$canBeImpersonatedAttributes['style'] = 'display: block;';

if ($canBeImpersonated->isChecked()) {
    $canBeImpersonatedAttributes['checked'] = 'checked';
}

$canBeImpersonated->setAttributes($canBeImpersonatedAttributes);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$form->prepare();
?>

<h1>Edit Role <?= $this->escapeHtml($role->getName()) ?></h1>

<p>
<a class="btn btn-default" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">
  <span class="glyphicon glyphicon-check"></span> Edit Permissions
</a>
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('inherit_roles')); ?>
            <?= $this->formElement($form->get('inherit_roles')); ?>
            <?= $this->formElementErrors($form->get('inherit_roles')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('canImpersonate')); ?>
            <?= $this->formElement($form->get('canImpersonate')); ?>
            <?= $this->formElementErrors($form->get('canImpersonate')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('canBeImpersonated')); ?>
            <?= $this->formElement($form->get('canBeImpersonated')); ?>
            <?= $this->formElementErrors($form->get('canBeImpersonated')); ?>
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

